### ISSUE TITLE
Multiple evalcontract

### ISSUE THREAD

**Issue by ThorvaldAagaard** [dealerv2/Dealer-Version-2-#8]
In the documentation:

**evalcontract** ( side, contract, vuln ) The evalcontract action will cause Dealer to use DDS to find the
number of tricks that can be taken in the given strain by the given side, for each 'interesting' deal. You
can evaluate a total of 10 different contracts; one in each strain per side. But in each contract for each
side you can evaluate only one 'flavor' from the six possibilities of undoubled: vul and nonvul,
doubled:vul and nonvul, and redoubled: vul and nonvul. So that while it is possible to compare say
3Hx to 1N, it is not possible to compare 3Hx to 3Hxx or even to 4H undoubled since there is only one
set of counters per strain per side. If you are specifying 5 or more evalcontract statements, you should
set the -M mode switch to 2 on the command line. (see command line switches later.)

So I assumed this would be valid
```
generate 1000000000
produce 500
predeal south SAKQT, H975, D862, CAK2
condition
	hcp(north) > 8 and hcp(north) < 15 and hearts(north) == 4 and diamonds(north) == 6
action 
evalcontract ( NS , z5D , vul ),
evalcontract ( NS , z3N , vul ),
evalcontract ( NS , z6D , vul )
```
but it generates
```
Contract  5D  V by  NS Average Result =   710.08, Success pct=  131.20, Fail pct=   68.80
Contract  3N  V by  NS Average Result =   626.38, Success pct=   95.80, Fail pct=    4.20
Contract  6D  V by  NS Average Result =   743.68, Success pct=   70.40, Fail pct=  129.60
```
While evaluating each contract in different runs it works fine

**Comment by dealerv2** [comment]
The documentation is perhaps not quite clear. I will have to double check the wording.
But this is not a bug, as the code is written.
Here is the relevant wording from the paragraph you quoted:
You can evaluate a total of 10 different contracts; one in each strain per side
The problem is that you have two contracts in the same strain for NS.(5D and 6D) There is one set of counters per side per strain. So what is happening is that the counts for the 5D and the counts for the 6D are both going to the 'diamond north/south' counter and you are in effect counting some of the tricks twice.

A more general approach would require creating a set of counters for each contract requested at run time, and then modifying the parser to keep track accordingly.

JGM.


________________________________
From: Thorvald Aagaard ***@***.***>
Sent: 24 March 2022 16:56
To: dealerv2/Dealer-Version-2- ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dealerv2/Dealer-Version-2-] Multiple evalcontract (Issue #8)


In the documentation:

evalcontract ( side, contract, vuln ) The evalcontract action will cause Dealer to use DDS to find the
number of tricks that can be taken in the given strain by the given side, for each 'interesting' deal. You
can evaluate a total of 10 different contracts; one in each strain per side. But in each contract for each
side you can evaluate only one 'flavor' from the six possibilities of undoubled: vul and nonvul,
doubled:vul and nonvul, and redoubled: vul and nonvul. So that while it is possible to compare say
3Hx to 1N, it is not possible to compare 3Hx to 3Hxx or even to 4H undoubled since there is only one
set of counters per strain per side. If you are specifying 5 or more evalcontract statements, you should
set the -M mode switch to 2 on the command line. (see command line switches later.)

So I assumed this would be valid

generate 1000000000
produce 500
predeal south SAKQT, H975, D862, CAK2
condition
        hcp(north) > 8 and hcp(north) < 15 and hearts(north) == 4 and diamonds(north) == 6
action
evalcontract ( NS , z5D , vul ),
evalcontract ( NS , z3N , vul ),
evalcontract ( NS , z6D , vul )


but it generates

Contract  5D  V by  NS Average Result =   710.08, Success pct=  131.20, Fail pct=   68.80
Contract  3N  V by  NS Average Result =   626.38, Success pct=   95.80, Fail pct=    4.20
Contract  6D  V by  NS Average Result =   743.68, Success pct=   70.40, Fail pct=  129.60


While evaluating each contract in different runs it works fine

**Comment by pgmer6809** [comment]
****

**Comment by dealerv2** [comment]
As stated above, and in the User Guide, it is a limitation of the program that you cannot evaluate two contracts in the same strain for the same side. 
_**You can evaluate a total of 10 different contracts; one in each strain per side**_
Here the user had one contract in 5D and one contract in 6D. Both of these contracts will use the same set of counters so some of the Diamond tricks will be counted twice leading to erroneous results.
